#!/usr/bin/env bash
# Script to configure domain zone and display subdomain information

domain=$1

# Check if a specific subdomain was provided
if [ "$#" -eq 2 ]; then
    sub=("$2")
else
    sub=("www" "lb-01" "web-01" "web-02")
fi

# Loop through the subdomains and display information
for subdomain in "${sub[@]}"; do
    echo -n "The subdomain $subdomain"
    dig "$subdomain.$domain" +short | awk '{ print " is a A record and points to " $1 }'
done
